// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBXQLzo_Gb2yIKQ6Vhw8Kqd00bUPczYRI',
    appId: '1:918346248228:web:6120a29f1dc7b9e7ee68b1',
    messagingSenderId: '918346248228',
    projectId: 'tracker-a9e0a',
    authDomain: 'tracker-a9e0a.firebaseapp.com',
    storageBucket: 'tracker-a9e0a.firebasestorage.app',
    measurementId: 'G-L3ZQ90FXC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFnujYfBVmWsqwg46Z2VUP5vDWzOUnU18',
    appId: '1:918346248228:android:4936fc41768b243dee68b1',
    messagingSenderId: '918346248228',
    projectId: 'tracker-a9e0a',
    storageBucket: 'tracker-a9e0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk9XQD4PXqGnnOuGUETNH7DlaLr3EQHi8',
    appId: '1:918346248228:ios:710661c8ffa92c64ee68b1',
    messagingSenderId: '918346248228',
    projectId: 'tracker-a9e0a',
    storageBucket: 'tracker-a9e0a.firebasestorage.app',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk9XQD4PXqGnnOuGUETNH7DlaLr3EQHi8',
    appId: '1:918346248228:ios:710661c8ffa92c64ee68b1',
    messagingSenderId: '918346248228',
    projectId: 'tracker-a9e0a',
    storageBucket: 'tracker-a9e0a.firebasestorage.app',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBXQLzo_Gb2yIKQ6Vhw8Kqd00bUPczYRI',
    appId: '1:918346248228:web:7663fce65cda6278ee68b1',
    messagingSenderId: '918346248228',
    projectId: 'tracker-a9e0a',
    authDomain: 'tracker-a9e0a.firebaseapp.com',
    storageBucket: 'tracker-a9e0a.firebasestorage.app',
    measurementId: 'G-1BWY5SNH4F',
  );
}
